### ISSUE TITLE
ISSUE: Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by johnnyl6** [FutureTense/keymaster#105]
**Describe the bug**
Errors in log otherwise working properly

**Environment (please complete the following information):**

- OS: ubuntu
- Type of device: NUC
- Home Assistant version: 2021.2.3
- Docker
- Component version: 0.0.24

**Logs**
```
2021-03-03 12:43:59 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/keymaster/helpers.py", line 296, in handle_state_change
alarm_level_value = int(alarm_level_state.state) if alarm_level_state else None
ValueError: invalid literal for int() with base 10: 'unknown'
2021-03-03 12:46:54 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/keymaster/helpers.py", line 296, in handle_state_change
alarm_level_value = int(alarm_level_state.state) if alarm_level_state else None
ValueError: invalid literal for int() with base 10: 'unknown'
```

**Screenshots**
N/A

**Additional context**
These error logs appearing a few times a day which does not seem to prevent keymaster working properly.

**Comment by raman325** [comment]
Fixed in the linked PR!
