### ISSUE TITLE
ISSUE: Error doing job: Future exception was never retrieved (new in v 0.0.25)

### ISSUE THREAD

**Issue by johnnyl6** [FutureTense/keymaster#112]
**Describe the bug**
Errors appearing in log. It's similar to previous bug fixed, but slightly different  

      ValueError: invalid literal for int() with base 10: 'unavailable

It used to be:
      ValueError: invalid literal for int() with base 10: 'unknown'

**Environment (please complete the following information):**

- OS: ubuntu
- Type of device: nuc
- Home Assistant version: 2021.3.0
- docker
- Component version: 0.0.25

**Logs**
```
2021-03-03 18:49:01 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/keymaster/helpers.py", line 297, in handle_state_change
int(alarm_level_state.state)
ValueError: invalid literal for int() with base 10: 'unavailable
2021-03-03 18:59:57 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/keymaster/helpers.py", line 297, in handle_state_change
int(alarm_level_state.state)
ValueError: invalid literal for int() with base 10: 'unavailable'
```

**Screenshots**
N/A

**Additional context**
N/A

**Comment by raman325** [comment]
Thanks for the report. This will get released as soon as I can resolve the other open issue
