### ISSUE TITLE
ISSUE: Stuck at "Adding"

### ISSUE THREAD

**Issue by jjmuriel** [FutureTense/keymaster#188]
**Describe the bug**
Stuck at "Adding" (see the attached picture)

**Environment (please complete the following information):**

- OS: Debian GNU/Linux 10 (buster)
- Type of system that HA is running on: Home Assistant Supervised
- Home Assistant version: core-2021.6.6
- Hassio/Docker/Core?: Core
- Component version: keymaster v0.0.51
- Z-Wave integration name: Z-Wave JS 2 MQTT
- Lock make and model: Schlage BE469ZP

**Logs**
This is the log when I execute the service "zwave_js.clear_lock_usercode" via Developer Tools

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: components/zwave_js/lock.py:134
First occurred: 14:12:46 (1 occurrences)
Last logged: 14:12:46

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: userIdStatus for code slot 3 not found
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 666, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/lock.py", line 134, in async_clear_lock_usercode
    await clear_usercode(self.info.node, code_slot)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/util/lock.py", line 99, in clear_usercode
    value = get_code_slot_value(node, code_slot, LOCK_USERCODE_STATUS_PROPERTY)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/util/lock.py", line 32, in get_code_slot_value
    raise NotFoundError(f"{property_name} for code slot {code_slot} not found")
zwave_js_server.exceptions.NotFoundError: userIdStatus for code slot 3 not found
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17131600/123155317-93030e80-d42d-11eb-8aee-01e30aae8428.png)

![image](https://user-images.githubusercontent.com/17131600/123156065-7adfbf00-d42e-11eb-8ac2-2424bfcad628.png)

![image](https://user-images.githubusercontent.com/17131600/123156281-baa6a680-d42e-11eb-9499-94543bf5b1c0.png)

**Additional context**
 The sensor.door_lock_code_slot_x entities are unavailable.

**Comment by firstof9** [comment]
Re-interview your lock

**Comment by jjmuriel** [comment]
> Re-interview your lock

I did this procedure twice via the Z-Wave JS 2 MQTT Panel, but I get the same error.

This is the Debug Message from Z-Wave JS 2 MQTT

```
2021-06-23 14:54:25.883 ERROR ZWAVE: Interview of node 5 has failed: Attempt 3/5 failed
```

And after the re-interview, the lock has this entities:
![image](https://user-images.githubusercontent.com/17131600/123160015-50443500-d433-11eb-86a4-da193cab5d84.png)

**Comment by firstof9** [comment]
Failed attempts usually mean poor signal or bad routing. Try a node heal as well.
You should have entries under "User Code" similar to this per code slot:
![image](https://user-images.githubusercontent.com/1105672/123160199-beccc700-d422-11eb-901c-545e44f46d7c.png)

**Comment by jjmuriel** [comment]
Thank you I'll try. In this moment there is not "User Code" section under the Lock in  Z-Wave JS 2 MQTT Panel.

**Comment by firstof9** [comment]
Yup that'd be the issue the CommandClass isn't getting discovered due to some issue.

**Comment by jjmuriel** [comment]
If the healing process doesn't work I'll re-engage the door lock. Thank you again

**Comment by FutureTense** [comment]
Out of scope
