### ISSUE TITLE
ISSUE: Initial setup fails with errors after first/fresh install

### ISSUE THREAD

**Issue by micahp2** [FutureTense/keymaster#197]
**Describe the bug**
After the very first install of KeyMaster, via HACS, multiple error messages are thrown in the log and the integration for KeyMaster fails to start. The error text via the log is shown below. Multiple full system reboots were tried with the same errors occurring each time.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: NUC 10 i7
- Home Assistant version: 6.1 
- Core core-2021.7.1
- Component version: v0.0.53
- Z-Wave integration name: zwave_js
- Lock make and model: Schlage BE469

**Logs**

Logger: homeassistant.config_entries
Source: core.py:1438
First occurred: 10:11:38 PM (1 occurrences)
Last logged: 10:11:38 PM

Error setting up entry frontdoor for keymaster
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/keymaster/__init__.py", line 266, in async_setup_entry
    await async_reset_code_slot_if_pin_unknown(
  File "/config/custom_components/keymaster/helpers.py", line 420, in async_reset_code_slot_if_pin_unknown
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1438, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service script.frontdoor_reset_codeslot

**Screenshots**
N/A

**Additional context**
Lock was minimally functional with zwave_js prior to KeyMaster install. Snapshot of system was taken prior to HACS install so it may be possible to roll back to before this issue occurred, if necessary.

**Comment by firstof9** [comment]
Check your home-assistant.log file for the real error.

**Comment by micahp2** [comment]
This appears to be all of the pertinent errors from the log:

2021-07-10 22:18:33 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration keymaster which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-10 22:18:33 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-10 22:18:36 WARNING (MainThread) [homeassistant.config_entries] Config entry 'FreeBSD router' for upnp integration not ready yet: None; Retrying in background
2021-07-10 22:18:36 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry frontdoor for keymaster
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/keymaster/__init__.py", line 266, in async_setup_entry
    await async_reset_code_slot_if_pin_unknown(
  File "/config/custom_components/keymaster/helpers.py", line 420, in async_reset_code_slot_if_pin_unknown
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1438, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service script.frontdoor_reset_codeslot
2021-07-10 22:18:38 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-gap-card - Repository is archived.
2021-07-10 22:18:38 ERROR (MainThread) [custom_components.hacs] bieniu/ha-airly - Repository is archived.
2021-07-10 22:18:38 ERROR (MainThread) [custom_components.hacs] mammuth/ha-fritzbox-tools - Repository is archived.
2021-07-10 22:18:38 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-dummy-entity-row - Repository is archived.
2021-07-10 22:18:38 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-gui-sandbox - Repository is archived.

**Comment by firstof9** [comment]
Try regenerating the package files.

**Comment by micahp2** [comment]
After fussing with it for several hours I decided it's better to just roll back to before HACS and live with the minimal functionality. Thanks for the suggestions, though.

**Comment by RobSheppard1976** [comment]
FWIW, I am seeing this too. Here's my homeassistant.log:

```
2021-07-11 13:32:50 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration keymaster which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-11 13:32:50 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-11 13:32:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry frontdoor for keymaster
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/keymaster/__init__.py", line 266, in async_setup_entry
    await async_reset_code_slot_if_pin_unknown(
  File "/config/custom_components/keymaster/helpers.py", line 420, in async_reset_code_slot_if_pin_unknown
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1438, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service script.frontdoor_reset_codeslot
```

I removed the integration, then removed from HACS and tried setting it all up again. I keep coming back to this error.

**Comment by raman325** [comment]
This is valid, the issue started when we renamed the automations. PR incoming
