### ISSUE TITLE
ISSUE: Setup failed for keymaster: unknown error

### ISSUE THREAD

**Issue by tykeal** [FutureTense/keymaster#215]
**Describe the bug**
Getting a debug dump during startup after upgrading to HA 2021.8.0

**Environment (please complete the following information):**

- OS: HassOS 6.2
- Type of system that HA is running on: RPi4 8G
- Home Assistant version: 2021.8.0
- Hassio/Docker/Core? Core
- Component version: 0.0.56
- Z-Wave integration name: zwave_js
- Lock make and model: Kwikset 912, Kwikset, 912, Kwikset 914

**Logs**
```
2021-08-04 08:54:19 ERROR (MainThread) [homeassistant.setup] Setup failed for keymaster: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 201, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/keymaster/__init__.py", line 30, in <module>
    from .binary_sensor import generate_binary_sensor_name
  File "/config/custom_components/keymaster/binary_sensor.py", line 219, in <module>
    class OZWNetworkReadySensor(BaseNetworkReadySensor):
  File "/config/custom_components/keymaster/binary_sensor.py", line 229, in OZWNetworkReadySensor
    def async_check_ozw_status(self, msg: models.Message):
AttributeError: module 'homeassistant.components.mqtt.models' has no attribute 'Message'
```

**Additional context**
Just upgraded to Home Assistant 2021.8.0 and was looking over the log to see if there were any issues. I found the above log and after giving HA another restart got it again.

I _do_ have the zwave_js to mqtt addon installed, but it is not enabled or being used. Also, the mosquitto broker addon is installed, but I haven't started doing anything with it yet.

**Comment by firstof9** [comment]
Update to the latest pre-release (beta) version.

Dupe #209

**Comment by tykeal** [comment]
Any idea when an official release with the fix is going to come out?

**Comment by firstof9** [comment]
It is the official release, we had to mark it "pre-release" because it isn't compatible with 2021.7.x and lower.

**Comment by tykeal** [comment]
hmm.... that's going to make it hard for people to find that it's there. I generally avoid installing things as beta if I'm not the developer ;)

That being said. I did install it and, yes, it fixed this issue.

**Comment by firstof9** [comment]
I'll move it back to release, since it's not technically beta.
