### ISSUE TITLE
Setup failed for keymaster: unknown error - Breaking change with Home Assistant 2021.8.0?

### ISSUE THREAD

**Issue by quadhammer** [FutureTense/keymaster#216]
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/keymaster/binary_sensor.py:229
Integration: keymaster (documentation, issues)
First occurred: 12:26:04 PM (1 occurrences)
Last logged: 12:26:04 PM

Setup failed for keymaster: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 201, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/keymaster/__init__.py", line 30, in <module>
    from .binary_sensor import generate_binary_sensor_name
  File "/config/custom_components/keymaster/binary_sensor.py", line 219, in <module>
    class OZWNetworkReadySensor(BaseNetworkReadySensor):
  File "/config/custom_components/keymaster/binary_sensor.py", line 229, in OZWNetworkReadySensor
    def async_check_ozw_status(self, msg: models.Message):
AttributeError: module 'homeassistant.components.mqtt.models' has no attribute 'Message'

**Comment by quadhammer** [comment]
and fixed with the update already!

Thank you
