### ISSUE TITLE
Unable to setup keymaster - config flow could not be loaded 

### ISSUE THREAD

**Issue by garyt72** [FutureTense/keymaster#217]
**Describe the bug**
Unable to add keymaster after installing via HACS.  When attempting to add from the integrations page I get an Error popup stating "Config flow could not be loaded".

**Environment (please complete the following information):**

- OS: Ubuntu 18.04
- Type of system that HA is running on: Ubuntu VM running on QNAP Virtualization Station
- Home Assistant version: 2021.8.6
- HA Core
- Component version: v0.0.59
- Z-Wave integration name: zwave_js
- Lock make and model: Schlage BE469

**Logs**
```
2021-08-11 21:03:24 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/srv/hass/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/srv/hass/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/srv/hass/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/http/forwarded.py", line 84, in forwarded_middleware
    return await handler(request)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/config_entries.py", line 696, in async_create_flow
    integration.get_platform("config_flow")
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/hass/conf/custom_components/keymaster/__init__.py", line 30, in <module>
    from .binary_sensor import generate_binary_sensor_name
  File "/srv/hass/conf/custom_components/keymaster/binary_sensor.py", line 33, in <module>
    from .helpers import (
  File "/srv/hass/conf/custom_components/keymaster/helpers.py", line 155, in <module>
    def get_code_slots_list(data: dict[str, int]) -> List[int]:
TypeError: 'type' object is not subscriptable

```

**Additional context**
Integration was working more than a month ago, but began running into issues.  Attempted to remove and re-install, but installation is now failing with the above error message and associated log entries.  I have tried completely uninstalling via HACS, confirmed the integration was completely removed, restarted HASS then reinstalling keymaster with no change in the outcome.

**Comment by raman325** [comment]
Are you perhaps running Python 3.9?

**Comment by raman325** [comment]
nevermind, I see the issue

**Comment by raman325** [comment]
@garyt72 try the latest, the issue should be resolved. And thanks for reporting

**Comment by garyt72** [comment]
Thank you for the fast response.  I can confirm that v0.0.60 does resolve the issue.

Strangely, after updating to 0.0.60 HACS wants me to "upgrade" from 0.0.60 to a "newer version" 0.0.59?

![keymaster_hacs](https://user-images.githubusercontent.com/38443372/129195079-d9e06d59-01d4-4479-82d8-4d1899180949.png)

**Comment by raman325** [comment]
thanks, not sure why that's happened but I pushed a new release which corrects the issue
