### ISSUE TITLE
ISSUE: "config flow could not be loaded"

### ISSUE THREAD

**Issue by cpw** [FutureTense/keymaster#220]
**Describe the bug**

I installed HACS (which was really really annoying) and then installed this. A large number of HA restarts later, and I try and add the "keymaster" integration. 
"config flow could not be loaded". (see #125 which looks similar but is closed without solution :( )

In the log files I see this:
```2021-08-23 15:29:45 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration keymaster: No module named 'openzwavemqtt'```

This is the only error I can find. Note that afterwards, I have to restart HA, as the "Add integration" button now just causes the UI to spin.

**Environment (please complete the following information):**

- OS: [e.g. HassOS/Raspbian/CentOS] Debian
- Type of system that HA is running on: [e.g. RPi3/NUC/Synology] Regular x86_64 server.
- Home Assistant version: [e.g. 0.105.5] 2021.8.6
- Hassio/Docker/Core? Core (venv)
- Component version: [e.g. 0.1.2] 0.6.1 I beleive
- Z-Wave integration name: [e.g. zwave_js] zwave_js
- Lock make and model: [e.g. Schlage BE469] Irrelevant

**Logs**
```2021-08-23 15:29:45 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration keymaster: No module named 'openzwavemqtt'```

**Screenshots**
![image](https://user-images.githubusercontent.com/1217211/130508524-c93a80a7-17ef-41dc-9e14-d36347e04bba.png)

**Additional context**
This is a fresh install of HACS and keymaster. I've just started playing with zwave and installed a lock today. It looked like this was going to be useful.

Commentary: I don't like HACS, but you provided NO alternative installation instructions for your extension. I have several other custom components that I track using _not HACS_. I wasn't very happy to have to install HACS to get yours.

**Comment by cpw** [comment]
Do note, I tried uninstall/reinstall, that didn't fix this problem.

**Comment by raman325** [comment]
offhand I can't figure out why this is occurring, the imports for `openzwavemqtt` should be such that if they fail, we handle it and it doesn't cause an error with setup

**Comment by raman325** [comment]
I just re-read your post... If you don't like the installation method, you are free to either:
- contribute manual installation documentation (it's the exact same process for installation, regardless of which custom component you use)
- find or develop another alternative

For 99.9% of users, HACS has proven to be the easiest method for installation which is why we have prioritized that. Again, if you've installed another custom component before, you can follow the same instructions for this one.

**Comment by cpw** [comment]
Understood. I don't know what the assets and autolock directories do, which is why i didn't do it the other way...

I've tried removing all references to openzwavemqtt and its still generating the error... I wonder where it's caching this..

**Comment by raman325** [comment]
I'm not sure. I found three files in our codebase that reference that module, and each of them is in a `try, except` block which is why removing those references didn't fix the issue. Do you have any other Z-Wave related integrations installed?

**Comment by cpw** [comment]
well, just the base zwavejs stuff, as far as I'm aware.

**Comment by cpw** [comment]
OK. I managed to extract a full stack trace for the import error :smile: 

```
Aug 24 19:03:37 house hass[23174]: 2021-08-24 19:03:37 ERROR (MainThread) [homeassistant.config_entries] No module named 'openzwavemqtt'
Aug 24 19:03:37 house hass[23174]: Traceback (most recent call last):
Aug 24 19:03:37 house hass[23174]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 696, in async_create_flow
Aug 24 19:03:37 house hass[23174]:     integration.get_platform("config_flow")
Aug 24 19:03:37 house hass[23174]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 498, in get_platform
Aug 24 19:03:37 house hass[23174]:     cache[full_name] = self._import_platform(platform_name)
Aug 24 19:03:37 house hass[23174]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 503, in _import_platform
Aug 24 19:03:37 house hass[23174]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Aug 24 19:03:37 house hass[23174]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Aug 24 19:03:37 house hass[23174]:     return _bootstrap._gcd_import(name[level:], package, level)
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Aug 24 19:03:37 house hass[23174]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:03:37 house hass[23174]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/__init__.py", line 10, in <module>
Aug 24 19:03:37 house hass[23174]:     from homeassistant.components.ozw import DOMAIN as OZW_DOMAIN
Aug 24 19:03:37 house hass[23174]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/ozw/__init__.py", line 7, in <module>
Aug 24 19:03:37 house hass[23174]:     from openzwavemqtt import OZWManager, OZWOptions
Aug 24 19:03:37 house hass[23174]: ModuleNotFoundError: No module named 'openzwavemqtt'
```

A second trace... whackamole!

```
Aug 24 19:06:59 house hass[23468]: 2021-08-24 19:06:59 ERROR (MainThread) [homeassistant.config_entries] No module named 'openzwavemqtt'
Aug 24 19:06:59 house hass[23468]: Traceback (most recent call last):
Aug 24 19:06:59 house hass[23468]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 696, in async_create_flow
Aug 24 19:06:59 house hass[23468]:     integration.get_platform("config_flow")
Aug 24 19:06:59 house hass[23468]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 498, in get_platform
Aug 24 19:06:59 house hass[23468]:     cache[full_name] = self._import_platform(platform_name)
Aug 24 19:06:59 house hass[23468]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 503, in _import_platform
Aug 24 19:06:59 house hass[23468]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Aug 24 19:06:59 house hass[23468]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Aug 24 19:06:59 house hass[23468]:     return _bootstrap._gcd_import(name[level:], package, level)
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Aug 24 19:06:59 house hass[23468]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:06:59 house hass[23468]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/__init__.py", line 30, in <module>
Aug 24 19:06:59 house hass[23468]:     from .binary_sensor import generate_binary_sensor_name
Aug 24 19:06:59 house hass[23468]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/binary_sensor.py", line 11, in <module>
Aug 24 19:06:59 house hass[23468]:     from homeassistant.components.ozw.const import DOMAIN as OZW_DOMAIN
Aug 24 19:06:59 house hass[23468]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/ozw/__init__.py", line 7, in <module>
Aug 24 19:06:59 house hass[23468]:     from openzwavemqtt import OZWManager, OZWOptions
Aug 24 19:06:59 house hass[23468]: ModuleNotFoundError: No module named 'openzwavemqtt'
```

A third error!

```
Aug 24 19:08:42 house hass[23665]: 2021-08-24 19:08:42 ERROR (MainThread) [homeassistant.config_entries] No module named 'openzwavemqtt'
Aug 24 19:08:42 house hass[23665]: Traceback (most recent call last):
Aug 24 19:08:42 house hass[23665]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 696, in async_create_flow
Aug 24 19:08:42 house hass[23665]:     integration.get_platform("config_flow")
Aug 24 19:08:42 house hass[23665]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 498, in get_platform
Aug 24 19:08:42 house hass[23665]:     cache[full_name] = self._import_platform(platform_name)
Aug 24 19:08:42 house hass[23665]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 503, in _import_platform
Aug 24 19:08:42 house hass[23665]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Aug 24 19:08:42 house hass[23665]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Aug 24 19:08:42 house hass[23665]:     return _bootstrap._gcd_import(name[level:], package, level)
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Aug 24 19:08:42 house hass[23665]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:08:42 house hass[23665]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/__init__.py", line 30, in <module>
Aug 24 19:08:42 house hass[23665]:     from .binary_sensor import generate_binary_sensor_name
Aug 24 19:08:42 house hass[23665]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/binary_sensor.py", line 12, in <module>
Aug 24 19:08:42 house hass[23665]:     from homeassistant.components.zwave.const import (
Aug 24 19:08:42 house hass[23665]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/zwave/__init__.py", line 40, in <module>
Aug 24 19:08:42 house hass[23665]:     from . import const, websocket_api as wsapi, workaround
Aug 24 19:08:42 house hass[23665]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/zwave/websocket_api.py", line 5, in <module>
Aug 24 19:08:42 house hass[23665]:     from homeassistant.components.ozw.const import DOMAIN as OZW_DOMAIN
Aug 24 19:08:42 house hass[23665]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/ozw/__init__.py", line 7, in <module>
Aug 24 19:08:42 house hass[23665]:     from openzwavemqtt import OZWManager, OZWOptions
Aug 24 19:08:42 house hass[23665]: ModuleNotFoundError: No module named 'openzwavemqtt'
```

Stack trace the fourth:
```
Aug 24 19:11:49 house hass[23918]: 2021-08-24 19:11:49 ERROR (MainThread) [homeassistant.config_entries] No module named 'openzwavemqtt'
Aug 24 19:11:49 house hass[23918]: Traceback (most recent call last):
Aug 24 19:11:49 house hass[23918]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 696, in async_create_flow
Aug 24 19:11:49 house hass[23918]:     integration.get_platform("config_flow")
Aug 24 19:11:49 house hass[23918]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 498, in get_platform
Aug 24 19:11:49 house hass[23918]:     cache[full_name] = self._import_platform(platform_name)
Aug 24 19:11:49 house hass[23918]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 503, in _import_platform
Aug 24 19:11:49 house hass[23918]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Aug 24 19:11:49 house hass[23918]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Aug 24 19:11:49 house hass[23918]:     return _bootstrap._gcd_import(name[level:], package, level)
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Aug 24 19:11:49 house hass[23918]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:11:49 house hass[23918]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/__init__.py", line 30, in <module>
Aug 24 19:11:49 house hass[23918]:     from .binary_sensor import generate_binary_sensor_name
Aug 24 19:11:49 house hass[23918]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/binary_sensor.py", line 33, in <module>
Aug 24 19:11:49 house hass[23918]:     from .helpers import (
Aug 24 19:11:49 house hass[23918]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/helpers.py", line 13, in <module>
Aug 24 19:11:49 house hass[23918]:     from homeassistant.components.ozw import DOMAIN as OZW_DOMAIN
Aug 24 19:11:49 house hass[23918]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/ozw/__init__.py", line 7, in <module>
Aug 24 19:11:49 house hass[23918]:     from openzwavemqtt import OZWManager, OZWOptions
Aug 24 19:11:49 house hass[23918]: ModuleNotFoundError: No module named 'openzwavemqtt'
```

The fifth element stack trace:
```
Aug 24 19:13:39 house hass[24138]: 2021-08-24 19:13:39 ERROR (MainThread) [homeassistant.config_entries] No module named 'openzwavemqtt'
Aug 24 19:13:39 house hass[24138]: Traceback (most recent call last):
Aug 24 19:13:39 house hass[24138]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 696, in async_create_flow
Aug 24 19:13:39 house hass[24138]:     integration.get_platform("config_flow")
Aug 24 19:13:39 house hass[24138]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 498, in get_platform
Aug 24 19:13:39 house hass[24138]:     cache[full_name] = self._import_platform(platform_name)
Aug 24 19:13:39 house hass[24138]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 503, in _import_platform
Aug 24 19:13:39 house hass[24138]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Aug 24 19:13:39 house hass[24138]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Aug 24 19:13:39 house hass[24138]:     return _bootstrap._gcd_import(name[level:], package, level)
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Aug 24 19:13:39 house hass[24138]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Aug 24 19:13:39 house hass[24138]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/__init__.py", line 84, in <module>
Aug 24 19:13:39 house hass[24138]:     from .services import (
Aug 24 19:13:39 house hass[24138]:   File "/home/homeassistant/.homeassistant/custom_components/keymaster/services.py", line 9, in <module>
Aug 24 19:13:39 house hass[24138]:     from homeassistant.components.ozw import DOMAIN as OZW_DOMAIN
Aug 24 19:13:39 house hass[24138]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/ozw/__init__.py", line 7, in <module>
Aug 24 19:13:39 house hass[24138]:     from openzwavemqtt import OZWManager, OZWOptions
Aug 24 19:13:39 house hass[24138]: ModuleNotFoundError: No module named 'openzwavemqtt'
```

**Comment by cpw** [comment]
So, after commenting out ALL of those references, I was able to get it to load! My guess is that if someone had previously setup the legacy zwave, it would work because those libraries would have been present. As I started from new with zwave_js, they've just never been present for me, so ozw/zwave cannot load and your hard references to them are problematic.

**Comment by raman325** [comment]
wow, great find! I see the problem now, will push a fix soon. Thanks for digging into this, without that trace I would not have been able to figure this one out

**Comment by raman325** [comment]
are you comfortable testing a branch? If so can you test this one: https://github.com/raman325/keymaster/tree/fix_imports

**Comment by cpw** [comment]
Yes, of course I would have had no problem testing a branch :smile: I'll update to latest and let you know. I'm sure this'll fix it though :grin:
