### ISSUE TITLE
ISSUE: User Locks are not functioning at all

### ISSUE THREAD

**Issue by phrreakk** [FutureTense/keymaster#278]
**Describe the bug**
New installation of Schlage z-wave lock and HA.  The lock functions in terms of locking via HA basic z-wave functionality.  When Keymaster is implemented, the locks are not able to be configured and it appears no user codes can be configured.

**Environment (please complete the following information):**

## System Health

version | core-2022.4.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4886
Installed Version | 1.24.5
Stage | running
Available Repositories | 1099
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 29.1 GB
disk_used | 5.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.57), chrony (2.3.0), SSH & Web Terminal (10.1.2), Let's Encrypt (4.12.2)

</details>

<details><summary>keymaster</summary>

zwave_integration | zwave_js
-- | --
network_status | on

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 1
mode | storage

</details>

- Z-Wave integration name: zwave_js
- Lock make and model: Schlage BE469ZP

**Logs**
2022-04-30 16:23:11 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities timer.keymaster_frontdoor_deadbolt_autolock
2022-04-30 16:23:11 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities script.keymaster_frontdoor_deadbolt_start_timer
2022-04-30 16:29:01 ERROR (MainThread) [custom_components.keymaster.services] Error calling zwave_js.set_lock_usercode service call: userCode for code slot 6 not found
2022-04-30 16:29:01 ERROR (MainThread) [homeassistant.components.automation.keymaster_synchronize_codeslot_frontdoor_deadbolt_6] keymaster_synchronize_codeslot_frontdoor_deadbolt_6: Choose at step 1: choice 1: Error executing script. Unexpected error for call_service at pos 1: userCode for code slot 6 not found
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/keymaster/__init__.py", line 224, in _add_code
await add_code(hass, entity_id, code_slot, usercode)
File "/config/custom_components/keymaster/services.py", line 155, in add_code
await call_service(
File "/config/custom_components/keymaster/services.py", line 94, in call_service
raise err
File "/config/custom_components/keymaster/services.py", line 89, in call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/zwave_js/lock.py", line 129, in async_set_lock_usercode
await set_usercode(self.info.node, code_slot, usercode)
File "/usr/local/lib/python3.9/site-packages/zwave_js_server/util/lock.py", line 112, in set_usercode
value = get_code_slot_value(node, code_slot, LOCK_USERCODE_PROPERTY)
File "/usr/local/lib/python3.9/site-packages/zwave_js_server/util/lock.py", line 32, in get_code_slot_value
raise NotFoundError(f"{property_name} for code slot {code_slot} not found")
zwave_js_server.exceptions.NotFoundError: userCode for code slot 6 not found
2022-04-30 16:29:01 ERROR (MainThread) [homeassistant.components.automation.keymaster_synchronize_codeslot_frontdoor_deadbolt_6] keymaster_synchronize_codeslot_frontdoor_deadbolt_6: Error executing script. Unexpected error for choose at pos 1: userCode for code slot 6 not found
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 761, in _async_choose_step
await self._async_run_script(script)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 838, in _async_run_script
await self._async_run_long_action(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 546, in _async_run_long_action
long_task.result()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1275, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/keymaster/__init__.py", line 224, in _add_code
await add_code(hass, entity_id, code_slot, usercode)
File "/config/custom_components/keymaster/services.py", line 155, in add_code
await call_service(
File "/config/custom_components/keymaster/services.py", line 94, in call_service
raise err
File "/config/custom_components/keymaster/services.py", line 89, in call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/zwave_js/lock.py", line 129, in async_set_lock_usercode
await set_usercode(self.info.node, code_slot, usercode)
File "/usr/local/lib/python3.9/site-packages/zwave_js_server/util/lock.py", line 112, in set_usercode
value = get_code_slot_value(node, code_slot, LOCK_USERCODE_PROPERTY)
File "/usr/local/lib/python3.9/site-packages/zwave_js_server/util/lock.py", line 32, in get_code_slot_value
raise NotFoundError(f"{property_name} for code slot {code_slot} not found")
zwave_js_server.exceptions.NotFoundError: userCode for code slot 6 not found
2022-04-30 16:29:01 ERROR (MainThread) [homeassistant.components.automation.keymaster_synchronize_codeslot_frontdoor_deadbolt_6] While executing automation automation.keymaster_synchronize_codeslot_frontdoor_deadbolt_6
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 515, in async_trigger
await self.action_script.async_run(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1275, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 761, in _async_choose_step
await self._async_run_script(script)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 838, in _async_run_script
await self._async_run_long_action(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 546, in _async_run_long_action
long_task.result()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1275, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/keymaster/__init__.py", line 224, in _add_code
await add_code(hass, entity_id, code_slot, usercode)
File "/config/custom_components/keymaster/services.py", line 155, in add_code
await call_service(
File "/config/custom_components/keymaster/services.py", line 94, in call_service
raise err
File "/config/custom_components/keymaster/services.py", line 89, in call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/zwave_js/lock.py", line 129, in async_set_lock_usercode
await set_usercode(self.info.node, code_slot, usercode)
File "/usr/local/lib/python3.9/site-packages/zwave_js_server/util/lock.py", line 112, in set_usercode
value = get_code_slot_value(node, code_slot, LOCK_USERCODE_PROPERTY)
File "/usr/local/lib/python3.9/site-packages/zwave_js_server/util/lock.py", line 32, in get_code_slot_value
raise NotFoundError(f"{property_name} for code slot {code_slot} not found")
zwave_js_server.exceptions.NotFoundError: userCode for code slot 6 not found

**Screenshots**
![snapshot_keymaster](https://user-images.githubusercontent.com/7446210/166122317-21a5b3bb-7ce1-4915-b004-aea035d9d1d1.png)

**Comment by firstof9** [comment]
` userCode for code slot 6 not found`

Re-interview your lock, your code slots are missing.

**Comment by jreed509** [comment]
I had the same problem with my Schlage BE469ZP's back on an older version of zwave_js. For me this problem is ended up being caused by an incomplete inclusion when using S0. For whatever reason, my locks just refused to properly transmit the usercodes during the inclusion process. After zwave_js added support for S2, I re-included my locks using S2 and this problem went away entirely. 

It might be worth excluding/reincluding to verify that S2 security is used instead of the legacy S0

**Comment by phrreakk** [comment]
It appears the zwave js integration doesn't know how to work with the BE469ZP.  I had it connected with zwave plus, after about 4-5 re-interviews...it lost the S2 code.  Now it doesn't see the battery level and other sensors.  The lock still works via the unlock/lock via HA...but it still doesn't work with Keymaster.  I think it is time to dump Schlage...I have had no problems with them in the past, which is sad.
![after_reset](https://user-images.githubusercontent.com/7446210/167170512-2726387c-71f4-4e53-9290-2be98ef08a3f.png)

**Comment by firstof9** [comment]
How many mains powered zwave nodes do you have?
This looks like signal issues.

**Comment by phrreakk** [comment]
I have an AEON z-stick ZW090 around 25-30 feet about from the front door lock.  I have two z-wave switches (Enlighten 46203) for my kitchen lighting system...those are right in the middle about 10-15 feet from the stick and front door.  I have an outlet (Minoston MP21Z) right next to the front door...literally 1 foot from the smart lock on the same wall.  The outlet works perfectly and never shows as being disconnected.

**Comment by firstof9** [comment]
You can try to do a heal on the node.

**Comment by kammerdiener** [comment]
So I am having a very similar problem to this. My node is staying secure though, but the User Codes are not being pulled into Home Assistant on the Lock. However, I can run the refresh codes script that KeyMaster provides and it does go and check all of the codes.

**Comment by firstof9** [comment]
Check your `home-assistant.log` for errors. If you are getting the `userCode for code slot X not found` message, your lock is missing the User Codes command class in zwavejs.

**Comment by phrreakk** [comment]
So I don't know if I resolved it or not...but it does seem to be working now.

I'm seeing these messages in the logs:

2022-05-09 15:17:44 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 28 not enabled
2022-05-09 15:17:45 ERROR (MainThread) [custom_components.keymaster] Unexpected error fetching keymaster data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/keymaster/__init__.py", line 602, in async_update_usercodes
    return await self._async_update()
  File "/config/custom_components/keymaster/__init__.py", line 639, in _async_update
    usercode_resp = await get_usercode_from_node(node, code_slot)
  File "/usr/local/lib/python3.9/site-packages/zwave_js_server/util/lock.py", line 105, in get_usercode_from_node
    ATTR_IN_USE: resp["userIdStatus"] == CodeSlotStatus.ENABLED,
TypeError: 'NoneType' object is not subscriptable
2022-05-09 15:17:45 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 8.725 seconds (success: False)
2022-05-09 15:17:50 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 1 value: #### (Prog code 1)
2022-05-09 15:17:50 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 2 value: #### (Prog code 2)
2022-05-09 15:17:50 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 3 not enabled
2022-05-09 15:17:50 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 4 not enabled
2022-05-09 15:17:50 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 5 not enabled
2022-05-09 15:17:50 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 6 not enabled
2022-05-09 15:17:50 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 7 not enabled
2022-05-09 15:17:50 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 8 not enabled
2022-05-09 15:17:50 DEBUG (MainThread) [custom_components.keymaster] DEBUG: Code slot 9 not enabled

I was able to add new codes and they showed up in the right slots.  

I decided to try a lower Security level so now I'm connecting at a lower level.  Apparently, zwavejs doesn't support that security level as mature as they should for that device.

![fixed_deadbolt](https://user-images.githubusercontent.com/7446210/167486812-f6c8354e-ec32-44a1-a696-1baa6431f298.png)

Thank you for the idea to try something different.
