### ISSUE TITLE
ZWaveJS.yaml giving error -- cannot complete install

### ISSUE THREAD

**Issue by trireme32** [FutureTense/keymaster#284]
I have the `zwave_js.yaml` file in my` /packages/additional_yaml `folder, and have `/packages` included in `config.yaml`.  I followed the directions to the letter.

On attempting to restart the server to complete the repo install, I get the following error:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:684
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:58:06 AM (2 occurrences)
Last logged: 11:00:40 AM

[281473334526400] The system cannot restart because the configuration is not valid: expected a dictionary for dictionary value @ data['packages']['automation']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 684, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: expected a dictionary for dictionary value @ data['packages']['automation']

```

**Comment by firstof9** [comment]
That yaml is no longer needed, which is why there's a big warning:

# 🚨🚨 **NOTE: These steps below are only needed for v0.0.22 and earlier. If you are on a later version, you can skip these steps** 🚨🚨

**Comment by trireme32** [comment]
OMG I have no idea how I missed that.  Rushing, I suppose.  My apologies.
