### ISSUE TITLE
ISSUE: "Error setting up entry FrontDoor for keymaster"

### ISSUE THREAD

**Issue by trireme32** [FutureTense/keymaster#285]
**Describe the bug**
Fresh install, getting the following error when installing the integration

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: HA Blue
- Home Assistant version: 2022.6.3
- Hassio
- Component version: 0.0.80
- Z-Wave integration name: zwave_js
- Lock make and model: Kwikset SmartCode 916

**Logs**
```
Logger: homeassistant.config_entries
Source: helpers/config_validation.py:541
First occurred: 12:13:06 PM (1 occurrences)
Last logged: 12:13:06 PM

Error setting up entry FrontDoor for keymaster
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/keymaster/__init__.py", line 267, in async_setup_entry
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1747, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/keymaster/__init__.py", line 243, in _generate_package
    generate_package_files(hass, name)
  File "/config/custom_components/keymaster/services.py", line 284, in generate_package_files
    if reload_package_platforms(hass):
  File "/config/custom_components/keymaster/helpers.py", line 391, in reload_package_platforms
    return asyncio.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/config/custom_components/keymaster/helpers.py", line 409, in async_reload_package_platforms
    await hass.services.async_call(domain, SERVICE_RELOAD, blocking=True)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 750, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 844, in execute_service
    await self._service_func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 270, in reload_service_handler
    if (conf := await component.async_prepare_reload()) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 281, in async_prepare_reload
    conf = await conf_util.async_hass_config_yaml(self.hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 354, in async_hass_config_yaml
    await merge_packages_config(hass, config, core_config.get(CONF_PACKAGES, {}))
  File "/usr/src/homeassistant/homeassistant/config.py", line 713, in merge_packages_config
    PACKAGES_CONFIG_SCHEMA(packages)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 541, in verify
    return cast(dict, schema(value))
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected a dictionary for dictionary value @ data['automation']

```

**Comment by firstof9** [comment]
What does your package config look like in your `configuration.yaml` file?

```yaml
homeassistant:
  packages: !include_dir_named packages
```

Is what we're expecting.

**Comment by trireme32** [comment]
Yes, I have that -- 
![Screenshot 2022-06-10 154751](https://user-images.githubusercontent.com/1649007/173139761-83bc937f-3a3e-4896-8ce1-43b8d32e9452.jpg)

**Comment by tykeal** [comment]
Issue for an old version no longer being supported.
