### ISSUE TITLE
ISSUE: Child locks (still) do not seem to work...

### ISSUE THREAD

**Issue by dubhunter** [FutureTense/keymaster#322]
**Describe the bug**
I am still getting errors with child locks, and the codes are not copied to the children. (Extension of https://github.com/FutureTense/keymaster/issues/319)

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: HA Blue (Odroid)
- Home Assistant version: 2023.1.6
- Hassio/Docker/Core: HassIO
- Component version: 0.0.84
- Z-Wave integration name: Z-Wave JS
- Lock make and model: Kwikset Home Connect 620s

**Logs**
```
2023-01-23 16:38:31.877 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities timer.keymaster_garage_side_door_autolock or it is/they are currently not available
2023-01-23 16:38:31.908 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_1_state_change] keymaster_override_parent_garage_side_door_1_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_1
2023-01-23 16:38:31.915 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_10_state_change] keymaster_override_parent_garage_side_door_10_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_10
2023-01-23 16:38:31.918 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_2_state_change] keymaster_override_parent_garage_side_door_2_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_2
2023-01-23 16:38:31.922 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_3_state_change] keymaster_override_parent_garage_side_door_3_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_3
2023-01-23 16:38:31.925 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_4_state_change] keymaster_override_parent_garage_side_door_4_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_4
2023-01-23 16:38:31.928 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_5_state_change] keymaster_override_parent_garage_side_door_5_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_5
2023-01-23 16:38:31.930 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_6_state_change] keymaster_override_parent_garage_side_door_6_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_6
2023-01-23 16:38:31.933 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_7_state_change] keymaster_override_parent_garage_side_door_7_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_7
2023-01-23 16:38:31.936 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_8_state_change] keymaster_override_parent_garage_side_door_8_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_8
2023-01-23 16:38:31.939 ERROR (MainThread) [homeassistant.components.automation.keymaster_override_parent_garage_side_door_9_state_change] keymaster_override_parent_garage_side_door_9_state_change: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_garage_side_door_copy_from_parent_9
2023-01-23 16:38:35.407 ERROR (MainThread) [custom_components.keymaster.services] Error calling script.keymaster_garage_side_door_copy_from_parent_1 service call: Unable to find service script.keymaster_garage_side_door_copy_from_parent_1
2023-01-23 16:38:35.444 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry garage_side_door for keymaster
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/keymaster/__init__.py", line 302, in async_setup_entry
    await init_child_locks(
  File "/config/custom_components/keymaster/services.py", line 63, in init_child_locks
    await call_service(hass, SCRIPT_DOMAIN, the_service)
  File "/config/custom_components/keymaster/services.py", line 77, in call_service
    raise err
  File "/config/custom_components/keymaster/services.py", line 72, in call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1702, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service script.keymaster_garage_side_door_copy_from_parent_1
```

**Screenshots**
<img width="1184" alt="Screenshot 2023-01-23 at 4 47 07 PM" src="https://user-images.githubusercontent.com/556503/214188780-d06f060a-a172-427c-a093-207bf743a2f6.png">
<img width="279" alt="Screenshot 2023-01-23 at 4 47 36 PM" src="https://user-images.githubusercontent.com/556503/214188933-4140a4da-f127-4e50-b496-d65a5c38f031.png">

**Comment by firstof9** [comment]
Try manually generating the scripts again from the `keymaster.generate` service call.

**Comment by dubhunter** [comment]
Ok, it looks like I was able to get everything working. Calling the service call did not seem to do it, but calling "reload" in the integration panel for the lock worked. (in addition to the reload, I had to clear out all the codes from the parent lock and re-add them).

I think there are still some bugs w/r/t deleting and re-adding locks, but they are not blocking me now with 0.0.84. Thanks!
