### ISSUE TITLE
ISSUE: Lock fails from HA Assist integration

### ISSUE THREAD

**Issue by chmeeedalf** [FutureTense/keymaster#336]
**Describe the bug**
Trying to lock my HC620 using the Home Assistant "Assist" integration I see the error

homeassistant.helpers.intent.IntentHandleError: Service turn_on does not support entity lock.home_connect_620_connected_smart_lock.

But Assist reports locked.

I'm not sure if this is a bug in Keymaster or a bug in HA Core, or both.

**Environment (please complete the following information):**

- OS: FreeBSD
- Type of system that HA is running on: HoneyComb LX2
- Home Assistant version: 2023.7.3
- Hassio/Docker/Core? Core
- Component version:  0.0.85
- Z-Wave integration name:  zwave_js
- Lock make and model: Kwikset HomeConnect 620

**Logs**
2023-08-06 13:23:35.273 ERROR (MainThread) [homeassistant.helpers.intent] Service call failed for lock.home_connect_620_connected_smart_lock
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/intent.py", line 467, in async_handle_states
    await service_coro
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 605, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/intent/__init__.py", line 89, in async_call_service
    raise intent.IntentHandleError(
homeassistant.helpers.intent.IntentHandleError: Service turn_on does not support entity lock.home_connect_620_connected_smart_lock

**Comment by firstof9** [comment]
Your trace back indicates an issue in HA.
