### ISSUE TITLE
ISSUE: Error setting up entry frontdoor for keymaster after restart HA

### ISSUE THREAD

**Issue by johnnyl6** [FutureTense/keymaster#81]
**Environment (please complete the following information):**

- OS: Home Assistant OS 5.11
- Type of device: RPi3B
- Home Assistant version: core-2021.2.2
- Hassio
- keymaster version: 0.0.16 from HACS
- zwave_js version: 0.1.6 

**Logs**
After initial clean install, keymaster works including notification
Restart HA core, got errors in log, and keymaster stopped working (PIN status stuck connecting....etc)

`
2021-02-10 20:23:26 INFO (MainThread) [custom_components.keymaster] Version v0.0.16 is starting, if you have any issues please report them here: https://github.com/FutureTense/keymaster
2021-02-10 20:23:26 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry frontdoor for keymaster
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/keymaster/__init__.py", line 129, in async_setup_entry
    primary_lock, child_locks = await generate_keymaster_locks(hass, config_entry)
  File "/config/custom_components/keymaster/helpers.py", line 152, in generate_keymaster_locks
    client = hass.data[ZWAVE_JS_DOMAIN][lock_config_entry_id][
KeyError: 'e961461237ef1328d13cae5c580aed45'
`

initial log while keymaster works before restart HA core: [initial_log.txt](https://github.com/FutureTense/keymaster/files/5963145/initial_log.txt)

**Screenshots**
Configuration
![image](https://user-images.githubusercontent.com/58282608/107602793-9a90ec00-6bdf-11eb-91d4-7ba66638180c.png)

**Comment by raman325** [comment]
Hi @johnnyl6 this issue has been reported before informally so clearly something is going on although at the moment I can't figure out what. can you look in `config/.storage/core.config_entries` and search for the key you mentioned (`e961461237ef1328d13cae5c580aed45`)? If you find it, verify that it's associated with `zwave_js`. If it isn't then we can try to solve that problem, but if it's there I may need to adjust the startup logic

**Comment by johnnyl6** [comment]
Hi @raman325 yes followed your instruction and found the "entry_id": "e961461237ef1328d13cae5c580aed45", in that file. It is associated with my zwave_js which is working properly. Thanks in advance for fixing this.🚀

**Comment by raman325** [comment]
are you comfortable pulling code down from here and installing it manually into your `custom_components` folder? If so, clone this repo https://github.com/raman325/keymaster/tree/resolve_key_error then checkout the `resolve_key_error` branch and install it manually. See if that resolves your issue

**Comment by johnnyl6** [comment]
Awesome! It's working well. Tested it with HA restarting and keymaster is still alive. The log also show your logic in place.👍
`
2021-02-11 21:23:23 INFO (MainThread) [custom_components.keymaster] Version v0.0.0 is starting, if you have any issues please report them here: https://github.com/FutureTense/keymaster
2021-02-11 21:23:23 INFO (MainThread) [custom_components.keymaster.helpers] Can't access Z-Wave JS data client yet. Trying again in 5 seconds
`

**Comment by raman325** [comment]
sweet!
